// data-live.js — IB proxy 客戶端（plain JS，走 window.* 全域模式）。
// 對應 repo 的 server/（FastAPI + ib_async，連本機 TWS / IB Gateway）。
// 所有函式失敗一律回 null：proxy 沒開、IB 沒連線、跨網域被擋 → 前端安靜 fallback 回 mock。
// proxy 位址可用 localStorage.setItem('ibProxyBase', 'http://...') 覆蓋。
(function () {
  const DEFAULT_BASE = 'http://127.0.0.1:8720';

  function base() {
    try {
      return localStorage.getItem('ibProxyBase') || DEFAULT_BASE;
    } catch (e) {
      return DEFAULT_BASE;
    }
  }

  async function get(path, timeoutMs) {
    const ctl = new AbortController();
    const timer = setTimeout(() => ctl.abort(), timeoutMs || 6000);
    try {
      const res = await fetch(base() + path, { signal: ctl.signal });
      if (!res.ok) return null;
      return await res.json();
    } catch (e) {
      return null;
    } finally {
      clearTimeout(timer);
    }
  }

  // ── End-of-day fallback ──────────────────────────────────────────────────
  // taifex-eod.js (generated by `server/taifex.py --write`) defines
  // window.TAIFEX_EOD: the previous session from TAIFEX alone — index close,
  // per-strike close / bid-ask / settlement / OI, real TX daily bars. When the
  // proxy is absent (the deployed site, a fresh checkout) every call below
  // answers from it instead of null, so the app shows real previous-session
  // numbers rather than mock. Stale snapshot (every expiry passed) → ignored.
  function dteOf(id) {
    const d = new Date(+id.slice(0, 4), +id.slice(4, 6) - 1, +id.slice(6, 8));
    const t = new Date(); t.setHours(0, 0, 0, 0);
    return Math.round((d - t) / 86400000);
  }
  function eod(pid) {
    const s = window.TAIFEX_EOD;
    if (!s || s.product !== pid || !s.expiries) return null;
    return s.expiries.some((e) => dteOf(e.id) >= 1) ? s : null;
  }
  function eodExpiries(s) {
    return s.expiries.map((e) => ({ id: e.id, label: e.label, dte: dteOf(e.id), type: e.type, date: e.date })).filter((e) => e.dte >= 1);
  }
  function eodOi(s, expiry) {
    const o = s.oi[expiry || (eodExpiries(s)[0] || {}).id];
    if (!o) return null;
    return {
      ...o, expiry: expiry, source: 'taifex',
      rows: o.rows.map((r) => ({ strike: r[0], call: { oi: r[1], oiChg: r[2], settle: r[3], prevSettle: r[4] }, put: { oi: r[5], oiChg: r[6], settle: r[7], prevSettle: r[8] } })),
    };
  }
  const live = {
    // { connected, source, ib:{...}, sinopac:{...} } | null
    // 帶 pid 時只回報「服務該商品的那個資料源」的狀態（IB 或永豐）。
    probe: (pid) => get('/api/health' + (pid ? '?pid=' + encodeURIComponent(pid) : ''), 2000),
    // { symbol, last, bid, ask, close, chgPct, month } | null
    quote: (pid) => get('/api/quote/' + encodeURIComponent(pid)),
    // [{ id, label, dte, type, date }] | null — id = YYYYMMDD
    expiries: (pid) => get('/api/expiries/' + encodeURIComponent(pid)),
    // { expiry, dte, underlying: { month, price }, rows: [...] } | null
    // rows 形狀跟 genChain 一致，元件可以直接吃。鏈要對 30+ 合約做行情快照，給長一點的 timeout。
    chain: (pid, expiry) => get('/api/chain/' + encodeURIComponent(pid) + '?expiry=' + encodeURIComponent(expiry), 30000),
    // { symbol, month, bar, bars: [{t,o,h,l,c,v}] } | null — 近月期貨歷史 K
    // opts: { bar: '1 day'|'1 hour'|'4 hours', duration: '1 M'|'3 M'|... }
    bars: (pid, opts) => {
      opts = opts || {};
      const q = [];
      if (opts.bar) q.push('bar=' + encodeURIComponent(opts.bar));
      if (opts.duration) q.push('duration=' + encodeURIComponent(opts.duration));
      if (opts.session) q.push('session=' + encodeURIComponent(opts.session)); // 'day' | 'full' — honored by sources with a night session
      return get('/api/bars/' + encodeURIComponent(pid) + (q.length ? '?' + q.join('&') : ''), 15000);
    },
    // { positions: [{ side, type, strike, premium(點數), qty, expiry, dte }] } | null
    // 唯讀持倉，用來把真實部位載入前端 legs。失敗一律 null（房間規則）。
    positions: (pid) => get('/api/positions/' + encodeURIComponent(pid), 8000),
    // { source, date, prevDate, expiry, rows: [{ strike, call: { oi, oiChg, vol, settle }, put }],
    //   maxCallOi: { strike, oi, oiChg }, maxPutOi, totals } | null
    // 每檔未平倉（TAIFEX 每日行情，前一交易日的數字）— 只有 products.js 標了 oiSource 的商品有。
    oi: (pid, expiry) => get('/api/oi/' + encodeURIComponent(pid) + (expiry ? '?expiry=' + encodeURIComponent(expiry) : ''), 15000),
    // { date, pcRatio: { ratio, chg, series: [{date, ratio}] }, foreign: { net, chg, ... },
    //   top10: { net, chg, specificNet, month } } | null — 籌碼（TAIFEX 每日，前一交易日）。
    market: (pid) => get('/api/market/' + encodeURIComponent(pid), 15000),
    // { source, weightsDate, date, rows: [{ rank, code, name, weight, close, chg, chgPct, open, high, low, vol }] } | null
    top20: (pid) => get('/api/top20/' + encodeURIComponent(pid), 15000),
    // { source, flow: 'tick-type' | 'tick-rule', date, month, day: { bars: [[hhmm,o,h,l,c,lots,cost,net,cum]…], high, low, cost, buy, sell, net }, night } | null
    intraday: (pid) => get('/api/intraday/' + encodeURIComponent(pid), 20000),
    // { source: 'twse', date, institutional: [{ name, buy, sell, net }] (NT$), margin: { 項目: { prev, today } } } | null — 前一交易日
    twse: (pid) => get('/api/twse/' + encodeURIComponent(pid), 15000),
    // { source: 'ib', asOf, marketDataType, rows: [{ key, symbol, localSymbol, exchange, last, prevClose, chg, chgPct, high, low, time, status }] } | null
    premarket: (pid) => get('/api/premarket/' + encodeURIComponent(pid), 15000),
  };
  // health.source 'eod' + a label tells the top bar what it is showing; no proxy ⇒ never "STALE".
  const fallback = {};
  fallback.probe = async (pid) => {
    const s = eod(pid);
    return s ? { connected: true, source: 'eod', label: 'TAIFEX ' + s.date.slice(5) + ' EOD', asOf: s.date } : null;
  };
  fallback.quote = async (pid) => {
    const s = eod(pid);
    if (!s) return null;
    const last = s.spot.price, ref = s.spot.ref;
    return { symbol: 'TXO', month: s.asOf.slice(0, 6), last, bid: null, ask: null, close: ref,
      chgPct: (last && ref) ? Math.round((last - ref) / ref * 10000) / 100 : null };
  };
  fallback.expiries = async (pid) => { const s = eod(pid); return s ? eodExpiries(s) : null; };
  fallback.chain = async (pid, expiry) => {
    const s = eod(pid);
    const c = s && s.chains[expiry];
    if (!c) return null;
    return { expiry, dte: dteOf(expiry), underlying: { month: s.asOf.slice(0, 6), price: s.spot.price }, rows: c.rows,
      oi: { source: 'taifex', date: s.date, prevDate: s.prevDate } };
  };
  fallback.bars = async (pid, opts) => {
    const s = eod(pid);
    if (!s || !s.bars || !s.bars.length || ((opts || {}).bar || '1 day') !== '1 day') return null;
    // 全日盤 = the night session that belongs to the same trading day + the day session.
    const full = (opts || {}).session === 'full' && s.barsFull && s.barsFull.length;
    return { symbol: 'TX', month: s.asOf.slice(0, 6), bar: '1 day', session: full ? 'full' : 'day', bars: full ? s.barsFull : s.bars };
  };
  fallback.oi = async (pid, expiry) => { const s = eod(pid); return s ? eodOi(s, expiry) : null; };
  fallback.market = async (pid) => { const s = eod(pid); return (s && s.market) || null; };
  fallback.top20 = async (pid) => { const s = eod(pid); return (s && s.top20) || null; };
  fallback.intraday = async (pid) => { const s = eod(pid); return (s && s.intraday) || null; };
  fallback.twse = async (pid) => { const s = eod(pid); return (s && s.twse) || null; };
  fallback.premarket = async (pid) => { const s = eod(pid); return (s && s.premarket) || null; };

  // Proxy first; the snapshot only answers when the proxy could not.
  window.LiveData = {};
  Object.keys(live).forEach((k) => {
    window.LiveData[k] = async (...args) => {
      const r = await live[k](...args);
      if (r != null) return r;
      return fallback[k] ? fallback[k](...args) : null;
    };
  });
})();
